# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tfstate-insighture"
    dynamodb_table = "tf-locks-insighture"
    encrypt        = true
    key            = "dev/ecs-task-scheduler/terraform.tfstate"
    profile        = "devops-sandbox"
    region         = "us-east-1"
  }
}
